version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "@gassantos"
    assignees:
      - "@gassantos"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      
  # C++ ecosystem (using cmake for now, could be extended)
  - package-ecosystem: "cmake"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 3
    reviewers:
      - "@gassantos"
    assignees:
      - "@gassantos"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "cmake"
      
  # Docker (when we add containerization)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 3
    reviewers:
      - "@gassantos"
    assignees:
      - "@gassantos"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
