name: Simple CI

on:
  workflow_dispatch:
  push:
    branches: [ main, develop ]

permissions:
  contents: read
  actions: read

jobs:
  quick-test:
    name: Quick Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev libgmock-dev
        
    - name: Setup Google Test
      run: |
        cd /usr/src/googletest
        sudo cmake -B build -DCMAKE_INSTALL_PREFIX=/usr/local
        sudo cmake --build build --target install
        
    - name: Build project
      run: |
        make clean
        make all
        
    - name: Build tests
      run: |
        make tests
        
    - name: Run tests
      run: |
        make run-tests
        
    - name: Test pipeline execution
      run: |
        timeout 60 make run || echo "Pipeline test completed"
